"""
BAEL Advanced Intelligence Package
====================================

Ultimate cognitive and reasoning capabilities.

"Intelligence without wisdom is merely computation." — Ba'el
"""

from .knowledge_fusion import (
    KnowledgeFusionEngine,
    KnowledgeGraph,
    ReasoningEngine,
    KnowledgeFusion,
    KnowledgeType,
    ConfidenceLevel,
    ReasoningMode,
    FusionStrategy,
    Entity,
    Relation,
    KnowledgeFragment,
    Inference,
    Query,
    QueryResult,
    knowledge_engine,
)

from .cognitive_reasoning import (
    CognitiveReasoningEngine,
    ThinkingEngine,
    ArgumentEngine,
    PerspectiveEngine,
    ProblemSolver,
    CognitiveMode,
    ThinkingLevel,
    ArgumentType,
    FallacyType,
    BiasType,
    Thought,
    Argument,
    Perspective,
    Problem,
    Solution,
    CognitiveState,
    cognitive_engine,
)

from .multimodal_processor import (
    MultiModalProcessor,
    ModalityDetector,
    TextParser,
    CodeParser,
    DataParser,
    MarkdownParser,
    Modality,
    ProcessingStage,
    ContentQuality,
    ModalitySignature,
    ParsedContent,
    TransformResult,
    IntegrationResult,
    multimodal_processor,
)

from .distributed_coordinator import (
    DistributedCoordinator,
    WorkerPool,
    TaskQueue,
    TaskScheduler,
    WorkerState,
    TaskState,
    TaskPriority,
    SchedulingStrategy,
    PartitionStrategy,
    Worker,
    Task,
    TaskGroup,
    ComputeResult,
    DistributedJobResult,
    distributed_coordinator,
)

__all__ = [
    # Knowledge Fusion
    "KnowledgeFusionEngine",
    "KnowledgeGraph",
    "ReasoningEngine",
    "KnowledgeFusion",
    "KnowledgeType",
    "ConfidenceLevel",
    "ReasoningMode",
    "FusionStrategy",
    "Entity",
    "Relation",
    "KnowledgeFragment",
    "Inference",
    "Query",
    "QueryResult",
    "knowledge_engine",
    # Cognitive Reasoning
    "CognitiveReasoningEngine",
    "ThinkingEngine",
    "ArgumentEngine",
    "PerspectiveEngine",
    "ProblemSolver",
    "CognitiveMode",
    "ThinkingLevel",
    "ArgumentType",
    "FallacyType",
    "BiasType",
    "Thought",
    "Argument",
    "Perspective",
    "Problem",
    "Solution",
    "CognitiveState",
    "cognitive_engine",
    # Multi-Modal
    "MultiModalProcessor",
    "ModalityDetector",
    "TextParser",
    "CodeParser",
    "DataParser",
    "MarkdownParser",
    "Modality",
    "ProcessingStage",
    "ContentQuality",
    "ModalitySignature",
    "ParsedContent",
    "TransformResult",
    "IntegrationResult",
    "multimodal_processor",
    # Distributed Computing
    "DistributedCoordinator",
    "WorkerPool",
    "TaskQueue",
    "TaskScheduler",
    "WorkerState",
    "TaskState",
    "TaskPriority",
    "SchedulingStrategy",
    "PartitionStrategy",
    "Worker",
    "Task",
    "TaskGroup",
    "ComputeResult",
    "DistributedJobResult",
    "distributed_coordinator",
]
